//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviseHR_Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeviseHR_Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        internal static string ASPNETCORE_ENVIRONMENT {
            get {
                return ResourceManager.GetString("ASPNETCORE_ENVIRONMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to postgresql://postgres:890899000@localhost:5432/DeviseHR?schema=public.
        /// </summary>
        internal static string DATABASE_URL {
            get {
                return ResourceManager.GetString("DATABASE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string EXPTIME {
            get {
                return ResourceManager.GetString("EXPTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5015.
        /// </summary>
        internal static string HR_CLIENT_PORT {
            get {
                return ResourceManager.GetString("HR_CLIENT_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5010.
        /// </summary>
        internal static string HR_PORT {
            get {
                return ResourceManager.GetString("HR_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HVgcxFE#%22#%#%$^*youIYyp897p98IOUPuLKjGtvnBCNhcglK:L&apos;iopI}0-jlkHKLHKJLJKFUY563#WYREHVgcxFE#%22#%#%$^*youIYyp897p98IOUPuLKjGtvnBCNhcglK:L&apos;iopI}0-HVgcxFE#%22#%#%$^*youIYyp897p98IOUPuLKjGtvnBCNhcglK:L&apos;iopI}0-jlkHKLHKJLJKFUY563#WYREHVgcxFE#%22#%#%$^*youIYyp897p98IOUPuLKjGtvnBCNhcglK:L&apos;iopI}0-HVgcxFE#%22#%#%$^*youIYyp897p98IOUPuLKjGtvnBCNhcglK:L&apos;iopI}0-jlkHKLHKJLJKFUY563#WYRE$#@r6765^&amp;567tYFfCBNcbncvGCJ.
        /// </summary>
        internal static string JWT_REFRESH_SECRET {
            get {
                return ResourceManager.GetString("JWT_REFRESH_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JhdjG78897&amp;*hDWewfhjJHuii()()90*789^^&amp;6%56rtRE#w3321@!#ER789*(UIJjhGHGFSXcVjkhaiuohRDIiu&amp;(*iJJKUIO78(iu()*^&amp;))).
        /// </summary>
        internal static string JWT_SECRET {
            get {
                return ResourceManager.GetString("JWT_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string LOGIN_ATTEPTS_ALLOWED {
            get {
                return ResourceManager.GetString("LOGIN_ATTEPTS_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5005.
        /// </summary>
        internal static string OP_CLIENT_PORT {
            get {
                return ResourceManager.GetString("OP_CLIENT_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15m.
        /// </summary>
        internal static string REG_EXPTIME {
            get {
                return ResourceManager.GetString("REG_EXPTIME", resourceCulture);
            }
        }
    }
}
